name: Deploy

on:
  push:
    branches: [ main ]
    
jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      
      - name: Compile CSS and JS
      - run: |
          npm install
          npm run prod
      
