name: Deploy

on:
  push:
    branches: [ staging ]
    
jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Compile CSS and JS
        run: |
          npm install
          npm run prod
      
